#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Apr 16, 2020 04:13:07 PM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top56 {base} {
    global vTcl
    if {$base == ""} {
        set base .top56
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #0080ff 
    wm focusmodel $top passive
    wm geometry $top 600x450+650+150
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Login"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    button $top.but57 \
        -activebackground #004b97 -activeforeground #f9f9f9 \
        -background #399cff -command login_test -disabledforeground #a3a3a3 \
        -font {-family {Berlin Sans FB Demi} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Login 
    vTcl:DefineAlias "$top.but57" "Button_login" vTcl:WidgetProc "Toplevel1" 1
    button $top.but58 \
        -activebackground #004b97 -activeforeground #fcfcfc \
        -background #399cff -disabledforeground #a3a3a3 \
        -font {-family {Berlin Sans FB Demi} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Cancel 
    vTcl:DefineAlias "$top.but58" "Button_cancel" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent59 \
        -background #399cff -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 264 
    vTcl:DefineAlias "$top.ent59" "Entry_userid" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab60 \
        -background #0080ff -disabledforeground #a3a3a3 \
        -font {-family {Berlin Sans FB Demi} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text {User Id} 
    vTcl:DefineAlias "$top.lab60" "Label_userid" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab61 \
        -background #0080ff -disabledforeground #a3a3a3 \
        -font {-family {Berlin Sans FB Demi} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text Password 
    vTcl:DefineAlias "$top.lab61" "Label_password" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent62 \
        -background #399cff -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 264 
    vTcl:DefineAlias "$top.ent62" "Entry_passwd" vTcl:WidgetProc "Toplevel1" 1
    labelframe $top.lab63 \
        -font TkDefaultFont -foreground black -background #0080ff -height 75 \
        -width 150 
    vTcl:DefineAlias "$top.lab63" "Labelframe_login" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab63
    label $site_3_0.lab64 \
        -background #0080ff -disabledforeground #a3a3a3 \
        -font {-family {ROG Fonts} -size 20} -foreground $vTcl(actual_gui_fg) \
        -text LOGIN 
    vTcl:DefineAlias "$site_3_0.lab64" "Label_lg" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab64 \
        -in $site_3_0 -x 10 -y 10 -width 127 -relwidth 0 -height 56 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab65 \
        -background #0080ff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) 
    vTcl:DefineAlias "$top.lab65" "Label_warning" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but57 \
        -in $top -x 0 -relx 0.367 -y 0 -rely 0.667 -width 89 -relwidth 0 \
        -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 0 -relx 0.55 -y 0 -rely 0.667 -width 86 -relwidth 0 \
        -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent59 \
        -in $top -x 0 -relx 0.333 -y 0 -rely 0.378 -width 264 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 0 -relx 0.117 -y 0 -rely 0.378 -width 0 -relwidth 0.133 \
        -height 0 -relheight 0.08 -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 0 -relx 0.117 -y 0 -rely 0.489 -width 0 -relwidth 0.147 \
        -height 0 -relheight 0.08 -anchor nw -bordermode ignore 
    place $top.ent62 \
        -in $top -x 0 -relx 0.333 -y 0 -rely 0.489 -width 264 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 0 -relx 0.367 -y 0 -rely 0.044 -anchor nw \
        -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx 0.233 -y 0 -rely 0.244 -width 0 -relwidth 0.42 \
        -height 0 -relheight 0.08 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top56 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

