#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Apr 24, 2020 01:10:23 PM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}



    menu .pop51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font {-family {Segoe UI} -size 10} \
        -foreground black -tearoff 1 
    vTcl:DefineAlias ".pop51" "Popupmenu1" vTcl:WidgetProc "" 1

proc vTclWindow.top66 {base} {
    global vTcl
    if {$base == ""} {
        set base .top66
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x450+650+150
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 152 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab68 \
        -activebackground #c0c0c0 -activeforeground #000000 \
        -background #c0c0c0 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text VIEW 
    vTcl:DefineAlias "$top.lab68" "Label1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu70 \
        -takefocus {} -text SHOW 
    vTcl:DefineAlias "$top.tBu70" "TButton1" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex72 \
        -background white -font {-family {Segoe UI Emoji} -size 10} \
        -foreground black -height 268 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 514 -wrap word 
    $top.tex72 configure -font "-family {Segoe UI Emoji} -size 10"
    $top.tex72 insert end text
    vTcl:DefineAlias "$top.tex72" "Text1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab68 \
        -in $top -x 0 -relx 0.083 -y 0 -rely 0.044 -width 0 -relwidth 0.872 \
        -height 0 -relheight 0.104 -anchor nw -bordermode ignore 
    place $top.tBu70 \
        -in $top -x 0 -relx 0.117 -y 0 -rely 0.2 -width 479 -relwidth 0 \
        -height 51 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tex72 \
        -in $top -x 0 -relx 0.1 -y 0 -rely 0.378 -width 0 -relwidth 0.857 \
        -height 0 -relheight 0.596 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top66 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

